# Generated by Django 4.2.4 on 2023-11-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProductosStoreApp", "0009_alter_producto_categoria_fk_and_more"),
        ("VentasStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleboletas",
            name="producto_FK",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ProductosStoreApp.producto",
            ),
        ),
    ]
