# Generated by Django 4.2.4 on 2023-11-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProveedoresStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="giro_FK",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ProveedoresStoreApp.giro",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="rubro_FK",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ProveedoresStoreApp.rubro",
            ),
        ),
    ]
