# Generated by Django 4.2.4 on 2023-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ProveedoresStoreApp",
            "0002_alter_proveedor_giro_fk_alter_proveedor_rubro_fk",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="correo_proveedor",
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
