# Generated by Django 4.2.6 on 2023-10-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientSharedApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
    ]
