# Generated by Django 4.2.4 on 2023-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DatosEmpresaStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datosempresa",
            name="minimo_boleta",
            field=models.IntegerField(default=100),
        ),
    ]
