# Generated by Django 4.2.4 on 2023-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DatosEmpresaStoreApp", "0002_datosempresa_minimo_boleta"),
    ]

    operations = [
        migrations.AddField(
            model_name="datosempresa",
            name="margen_global",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
