# Generated by Django 4.2.4 on 2023-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DatosEmpresaStoreApp", "0003_datosempresa_margen_global"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datosempresa",
            name="email",
            field=models.EmailField(default="pepe@gmail.com", max_length=64),
        ),
    ]
