# Generated by Django 4.2.4 on 2023-11-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "ClientesStoreApp",
            "0002_remove_cliente_comuna_fk_remove_cliente_razon_social_and_more",
        ),
        ("FacturasStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturas",
            name="cliente_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ClientesStoreApp.cliente",
            ),
        ),
    ]
