# Generated by Django 4.2.4 on 2023-11-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("FacturasStoreApp", "0003_alter_detallefacturas_factura_fk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallefacturas",
            name="factura_FK",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="FacturasStoreApp.facturas",
            ),
        ),
    ]
