# Generated by Django 4.2.6 on 2023-10-20 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id_regiones", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_region", models.CharField(max_length=45, unique=True)),
            ],
            options={
                "db_table": "region",
            },
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                ("id_comuna", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_comuna", models.CharField(max_length=45, unique=True)),
                (
                    "region_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClientesStoreApp.region",
                    ),
                ),
            ],
            options={
                "db_table": "comuna",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("run_cliente", models.CharField(max_length=15, unique=True)),
                ("nombre_cliente", models.CharField(max_length=45)),
                ("apellido_cliente", models.CharField(max_length=45)),
                ("correo_cliente", models.CharField(max_length=64, unique=True)),
                ("razon_social", models.CharField(max_length=45)),
                ("direccion", models.CharField(max_length=45)),
                (
                    "tipo_giro",
                    models.IntegerField(
                        choices=[(1, "Mayorista"), (2, "Minorista")], default=2
                    ),
                ),
                (
                    "comuna_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClientesStoreApp.comuna",
                    ),
                ),
            ],
            options={
                "db_table": "cliente",
            },
        ),
    ]
