# Generated by Django 4.2.4 on 2023-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ClientesStoreApp",
            "0002_remove_cliente_comuna_fk_remove_cliente_razon_social_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="correo_cliente",
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
