# Generated by Django 4.2.4 on 2023-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ComprasStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compras",
            name="tipo_impuesto",
            field=models.IntegerField(
                choices=[(1, "Con Impuesto"), (2, "Sin Impuesto")], default=1
            ),
        ),
    ]
