# Generated by Django 4.2.4 on 2023-11-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "ProveedoresStoreApp",
            "0002_alter_proveedor_giro_fk_alter_proveedor_rubro_fk",
        ),
        ("ComprasStoreApp", "0003_rename_descuento_compras_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compras",
            name="proveedor_FK",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ProveedoresStoreApp.proveedor",
            ),
        ),
    ]
