# Generated by Django 4.2.4 on 2023-11-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ProductosStoreApp", "0009_alter_producto_categoria_fk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promociones",
            fields=[
                ("id_promocion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
                ("descuento", models.IntegerField()),
                (
                    "producto_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ProductosStoreApp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "promociones",
            },
        ),
    ]
