# Generated by Django 4.2.4 on 2023-11-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PromocionesStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promociones",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
