# Generated by Django 4.2.4 on 2023-11-03 21:35

import ProductosStoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductosStoreApp", "0004_alter_producto_tipo_impuesto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=ProductosStoreApp.models.dynamic_upload_path,
            ),
        ),
    ]
