# Generated by Django 4.2.4 on 2023-11-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductosStoreApp", "0005_alter_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="tipo_medida",
            field=models.IntegerField(
                choices=[(1, "Unidad"), (2, "Kilo"), (3, "Litro")], default=1
            ),
        ),
    ]
