# Generated by Django 4.2.4 on 2023-11-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductosStoreApp", "0006_alter_producto_tipo_medida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=10),
        ),
    ]
