# Generated by Django 4.2.4 on 2023-11-16 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProductosStoreApp", "0008_alter_producto_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria_FK",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ProductosStoreApp.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="usuario_FK",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
