# Generated by Django 4.2.4 on 2023-11-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductosStoreApp", "0009_alter_producto_categoria_fk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="margen_ganancia",
            field=models.IntegerField(default=30),
        ),
    ]
