# Generated by Django 4.2.4 on 2023-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductosStoreApp", "0010_producto_margen_ganancia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="margen_ganancia",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
